return {}
--		-- Ajuda a procurar diretórios e arquivos
--	Plug 'nvim-lua/plenary.nvim'
--	Plug 'BurntSushi/ripgrep'
--	Plug ('nvim-telescope/telescope.nvim', { ['tag'] = '0.1.5' })
--	
--		-- Configurações de servidores de linguagens
--	Plug 'neovim/nvim-lspconfig'
--	Plug 'mfussenegger/nvim-dap'
--	Plug 'rcarriga/nvim-dap-ui'
--	Plug 'jose-elias-alvarez/null-ls.nvim'
--	Plug 'mhartington/formatter.nvim'
--	Plug 'natebosch/vim-lsc'
--	
--		-- Autocomplete
--	Plug ('neoclide/coc.nvim', { ['branch'] = 'release'})
--	
--		-- Flutter Config
--	Plug 'dart-lang/dart-vim-plugin'
--	Plug 'thosakwe/vim-flutter'

